---
kind: pipeline
type: kubernetes
name: default
steps:
- name: restore cache
  image: harbor.xirion.net/hub/plugins/s3-cache
  settings:
    pull: true
    endpoint: http://192.168.0.112:9000
    root: drone
    restore: true
    access_key:
      from_secret: MINIO_ACCESS_KEY
    secret_key:
      from_secret: MINIO_SECRET_KEY

- name: test rust
  image: harbor.xirion.net/library/rust-gcc
  commands:
  - export CARGO_HOME="$PWD/.cargo"
  - cargo test

- name: build release
  image: harbor.xirion.net/library/rust-gcc
  commands:
  - rm -rf ./target/release/dsmr
  - export CARGO_HOME="$PWD/.cargo"
  - cargo build -Z unstable-options --out-dir bin --release --frozen

- name: upload artifact
  image: harbor.xirion.net/hub/plugins/s3
  settings:
    bucket: public
    source: bin/*
    target: /artifacts/dsmr/
    path_style: true
    endpoint: http://192.168.0.112:9000
    acl: public-read
    access_key:
      from_secret: MINIO_ACCESS_KEY
    secret_key:
      from_secret: MINIO_SECRET_KEY
  
- name: rebuild cache
  image: harbor.xirion.net/hub/plugins/s3-cache
  settings:
    pull: true
    root: drone
    endpoint: http://192.168.0.112:9000
    access_key:
      from_secret: MINIO_ACCESS_KEY
    secret_key:
      from_secret: MINIO_SECRET_KEY
    rebuild: true
    mount:
      - target/
      - .cargo/
    when:
      event: push
